Fully Working Prototype with Bazel
googleinterns/java-function-coverage pull request #1
Opened 2020-09-03 15:39 UTC by muratekici

2020-09-07 10:58 UTC, pratyai commented
Thanks! Could you please format the .java files with https://github.com/google/google-java-format?

2020-09-07 11:34 UTC, pratyai requested changes

2020-09-07 11:34 UTC, pratyai commented on README.md
> +$ mvn package
We could drop mvn (configs and instructions), I think.

2020-09-07 11:34 UTC, pratyai commented on README.md
> +### Example Usage with Bazel
Building with Bazel should be the canonical way (instead of mvn). I think the Quickstart section could go something like:

## Quickstart

### With the included examples
* Build the funccover agent<link to concepts>:
< bulid command >
* Build the example handler<link to concepts>:
< build command >
* Build the example program:
< build command >
* Run the program:
< run command >

### With customization
* Build the funccover agent<link to concepts>:
< bulid command >
* Write an handler<link to concepts>:
< briefly explain how to write one, link the example handler >
* Build the program:
< just explain that the user can use whatever prebuild binary they have >
* Run the program:
< run command >

### Concepts
< overview, explain what's an agent,  what's a handler, etc. >

2020-09-07 11:55 UTC, cher11 approved these changes

2020-09-07 12:39 UTC, pratyai requested changes

2020-09-07 12:39 UTC, pratyai commented on src/main/java/com/funccover/CoverageTransformer.java
> +  // transform instruments given bytecode and returns instrumented bytecode
s/transform/Transform/ (i.e. capitalize); end the line with a period (i.e. ".").

2020-09-07 12:39 UTC, pratyai commented on src/main/java/com/funccover/CoverageTransformer.java
> +  // if it returns null, then given class will be loaded without instrumentation
s/if/If/ (i.e. capitalize); end the line with a period (i.e. ".").

2020-09-07 12:39 UTC, pratyai commented on src/main/java/com/funccover/CoverageTransformer.java
> +    // if we do not want to instrument given class, return null
s/if/If/ (i.e. capitalize); end the line with a period (i.e. ".").

2020-09-07 12:39 UTC, pratyai commented on src/main/java/com/funccover/CoverageTransformer.java
>  // CoverageTransformer implements a class that will be used in instrumentation
Please capitalize the first letter of the sentences in the comment and end with a period throughout all the files involved.

2020-09-07 12:39 UTC, pratyai commented on src/main/java/com/funccover/CoverageTransformer.java
> +    } catch (Throwable e) {
* Why "Throwable" instead of a more specific exception type?
* Why catch the exception at all? Are there "noise" exceptions where the behaviour of the instrumented program is not impacted?

2020-09-07 12:39 UTC, pratyai commented on src/main/java/com/funccover/HandlerLoader.java
> +    } catch (Exception e) {
Same comment about catching exceptions as the other comment.

2020-09-08 08:10 UTC, muratekici commented on src/main/java/com/funccover/CoverageTransformer.java
>  // CoverageTransformer implements a class that will be used in instrumentation
Last comment fix commit resolves this issue.

2020-09-08 08:10 UTC, muratekici commented on src/main/java/com/funccover/CoverageTransformer.java
> +  // transform instruments given bytecode and returns instrumented bytecode
here the name of the method is transform, should I make it Transform?

2020-09-08 08:42 UTC, pratyai commented on src/main/java/com/funccover/CoverageTransformer.java
> +  // transform instruments given bytecode and returns instrumented bytecode
Right; didn't notice it's the function name. Put in quotes, like `transform`, I guess.

2020-09-08 08:54 UTC, pratyai requested changes

2020-09-08 08:54 UTC, pratyai commented on WORKSPACE
> +)
Could you run buildifier (https://github.com/bazelbuild/buildtools) over bazel related files?

2020-09-08 09:37 UTC, muratekici commented on README.md
> +### Example Usage with Bazel
Can you check it, I updated readme.md

2020-09-08 09:48 UTC, muratekici commented on WORKSPACE
> +)
fixed

2020-09-08 09:52 UTC, muratekici commented on src/main/java/com/funccover/CoverageTransformer.java
> +    } catch (Throwable e) {
Well, I thought it would be better not exit instrumentation if it fails somewhere. I can change it. I don't think there are noise exceptions that just doesn't mean anything. .

2020-09-08 10:07 UTC, pratyai commented on README.md
> +
Add a line here:
This should generate the file `bazel-bin/src/main/java/example/handler/libHandler.jar` under the project root.

2020-09-08 10:07 UTC, pratyai commented on README.md
> +
Add a line here:
This should generate the file `bazel-bin/src/main/java/com/funccover/funccover_deploy.jar` under the project root.

2020-09-08 10:07 UTC, pratyai commented on README.md
> +$ bazel build --jvmopt="-javaagent:agent_path='jar:handler_path example.handler.Handler' "  //src/main/java/example/program:HelloWorld
I think agent_path and handler_path can be replaced with "bazel-bin/src/main/..." versions to allow just copying it (well, that works under the assumption that the command is run from the root; but that would be obvious to the reader at this point, I think).

2020-09-08 10:07 UTC, pratyai commented on src/main/java/com/funccover/CoverageTransformer.java
> +    } catch (Throwable e) {
I'm undecided about whether to abort to let the user know that the instrumentation didn't work, or to just continue. Let's keep it as it (i.e. with catching & ignoring exceptions) is for now.

2020-09-08 10:08 UTC, pratyai approved these changes

2020-09-08 10:09 UTC, pratyai commented
Please resolve the remaining comments; and let me know so that I can merge it. Thanks!

2020-09-08 10:40 UTC, muratekici commented on README.md
> +$ bazel build --jvmopt="-javaagent:agent_path='jar:handler_path example.handler.Handler' "  //src/main/java/example/program:HelloWorld
done

2020-09-08 10:40 UTC, muratekici commented on README.md
> +
done

2020-09-08 10:40 UTC, muratekici commented on README.md
> +
done

2020-09-08 10:56 UTC, pratyai commented
@muratekici One last request; could you please reformat the java files? The format checker is complaining. Thanks!

2020-09-08 10:58 UTC, muratekici commented
Checkers are fine now I think.

2020-09-08 10:59 UTC, merged